### ISSUE TITLE
Make mouse events touchscreen friendly

### ISSUE THREAD

**Issue by ChasNelson1990** [gliff-ai/annotate#161]
**Describe the bug**

Currently does not work when using touchscreen devices because everything is handled as a mouse event.

**To Reproduce**
Steps to reproduce the behaviour:

1.  Go to the app on a phone/tablet and try and do anything

**Expected behaviour**

It to work.

**Screenshots**

N/A

**Desktop (please complete the following information):**

Suggest we test on android and iOS devices.

**Additional context**

None

**Comment by joshuajames-smith** [comment]
## Describe the bug

- [ ] Currently can not use brush tool on touchscreen device (iPad). Instead of creating an annotation it treats the space as an image. 
- [ ] The tool bars do not entirely scale the smaller screen.

## To Reproduce

Steps to reproduce the behaviour:

1.  Go to ANNOTATE.
2.  Try and use brush tool to annotate an image.

## Expected behaviour

- [ ] Brush tool should be able to annotate on touchscreen devices.
- [ ] Tool bars should fit the available screen space.

## Screenshots

![IMG_0624](https://user-images.githubusercontent.com/83074763/133653827-09e9288e-f517-4a7b-b6ef-95b80ec95888.PNG)

## System Info (please complete the following information):

- OS: iPadOS 14.7.1
- Browser: Safari

## Additional context

N/A

**Comment by joshuajames-smith** [comment]
**ANNOTATE Tool Interactions**

Tool-tips currently rely on a hover interaction which will not work on a touchscreen device. 
Various options below for discussion:

1. Remove tool tips.

![Annotation - Touchscreen  Option 1](https://user-images.githubusercontent.com/83074763/133659498-f0ecb52d-7d58-458e-8c3f-a62a4ea0c696.png)

2. Long-press to reveal tool tip.

![Annotation - Touchscreen  Option 2](https://user-images.githubusercontent.com/83074763/133659521-9af957d3-39ea-4c2b-adab-f2a947abf987.png)

3. Pop-up which is activate upon a single press and is displayed next to the tool but is timed to disappear after a several seconds or if user clicks away.

![Annotation - Touchscreen  Option 3](https://user-images.githubusercontent.com/83074763/133659542-a191f034-d20f-4a4e-9491-7cfdfbf280ad.png)

4. Pop-up which is activate upon a single press and is displayed on the screen (top or bottom?).

![Annotation - Touchscreen  Option 4](https://user-images.githubusercontent.com/83074763/133659918-49edfc0b-4737-45df-93b7-9fe3bbe8a2d1.png)

5. Implement a tooltip button which allows users to press and then tap on a tool to see what it is but not active it.

![Annotation - Touchscreen  Option 5  – 1](https://user-images.githubusercontent.com/83074763/133659652-70c1252f-f019-4bf7-908c-a5c0cad3ec68.png)
![Annotation - Touchscreen  Option 5  – 2](https://user-images.githubusercontent.com/83074763/133659658-92e08967-394c-42cc-9f8a-18e86b2dab94.png)

**Comment by joshuajames-smith** [comment]
**Assigned Shortcuts**

Some users may use a keyboard with their touchscreen device and then could benefit from shortcut keys.
Do we remove it from touchscreen staging or can it potentially recognise a keyboard? If not do we leave shortcuts?
