### ISSUE TITLE
Style 3D slice slider

### ISSUE THREAD

**Issue by ChrisBaidoo** [gliff-ai/annotate#193]
**Is your feature request related to a problem? Please describe.**
The 3D image slice slider needs to be designed / styled in line with  the new identity. 

**Describe the solution you'd like**
Show the current slice of the image as you drag the slider. 

**Describe alternatives you've considered**
Have the minimum and the maximum number of slices at each end of the slider?

**Comment by joshuajames-smith** [comment]
The slider is taken from the UI/UX pattern of the brightness/contrast tool slider. The vertical slider should be placed top right. Again, the green box could allow uses to type in a specific value (as previously discussed, this can be a 'would be nice' rather than an immediate feature inclusion). The value in the green box represents the current slice. The top value of the slider is the max. slice number with the bottom value of the slide showing the min. slice number.

** The bar can be shortened if that helps with the space and fitting of the component into the layout.

![Interface Layout -  empty  - w- slider  mini-map open  v2](https://user-images.githubusercontent.com/83074763/121691806-53e4cd00-cabf-11eb-8fe7-39bc03d574c7.png)
![Interface Layout -  empty  -  w- slider  mini-map closed  v2](https://user-images.githubusercontent.com/83074763/121691820-55ae9080-cabf-11eb-92ab-81bb62368714.png)

https://xd.adobe.com/view/b8c275c7-a4f0-4904-b965-f21703101788-ed91/
https://xd.adobe.com/view/88414aae-93d2-4642-b6e7-848bdbfce291-dd12/
