### ISSUE TITLE
Inform the user when saving is completed

### ISSUE THREAD

**Issue by Kinukeo** [gliff-ai/annotate#502]
## Is your feature request related to a problem? Please describe

When saving is finished the saving box disappears, this makes it difficult to know if my project is saved.

## Describe the solution you'd like

I think it would be helpful if something stayed on the screen for a few seconds to inform the user that saving is completed.

## Additional context

The loading box also seems to disappear when loading is at 0%

**Comment by joshuajames-smith** [comment]
### Instances of Bug.

1. Single click on `Save Annotation` shows the purple snackbar at 0% but instantly closes it. Allowing this to continue, the purple snackbar would then reappear at 35% but instantly closes again before happening exactly the same at 70%.

2. Clicking and holding on `Save Annotation` keeps purple snackbar active with the progress actively moving from 0% > 35% > 70%.

### UI & UX Input.

The snackbar needs to remain open for the full saving process, so the user has good progress feedback about the back-end process of saving. The spinner should be moved to the left with the text on the right (slight edit to the copywriting). Another snackbar should appear once saving is complete (ideally just replaces the content of snackbar so there isn't a delay due to transition or closing and opening). This lets the users know it was successful.

![ANNOTATE -  saving - in progress](https://user-images.githubusercontent.com/83074763/149815823-14d164d4-adb0-44c2-89d1-0de2b8a3fc20.png)
![ANNOTATE -  saving - complete](https://user-images.githubusercontent.com/83074763/149815828-3f5e0aa9-8736-4a73-9a88-8be1431f7b13.png)
